export const metadata = {
  title: 'Joë "Seik" Martinez Montoya',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang='fr'>
      <body>{children}</body>
    </html>
  );
}
